baseURL: "https://bookstack.xnzone.vercel.app"
title: bookstack
paginate: 6
theme: bookstack

menu:
  main:
    - identifier: search
      name: Search
      url: search/
outputs:
    home:
        - HTML
        - JSON
sitemap:
  filename: sitemap.xml
  priority: 0.5
  changefreq: daily
enableRobotsTXT: true
